package com.blog.dao.mapper.gather;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.gather.GatherContent;

public interface GatherContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int insert(GatherContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int insertSelective(GatherContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    GatherContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GatherContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(GatherContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gather_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GatherContent record);
    //获取数量
	int getCount(@Param("isOnline")Integer isOnline,@Param("type") Integer type,@Param("isHot") Integer isHot,@Param("isTop") Integer isTop,@Param("start") Date start,@Param("end") Date end);
	//根据条件分页获取所有数据
	List<GatherContent> getContentByPage(@Param("isOnline")Integer isOnline,@Param("type") Integer type,@Param("isHot") Integer isHot,@Param("isTop") Integer isTop,@Param("start") Date start,@Param("end") Date end,@Param("pageStartNumber") int pageStartNumber,@Param("pageEndNumber") int pageEndNumber);
	
}