package com.blog.dao.mapper.log;

import com.blog.dao.bean.log.LogLogin;

public interface LogLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int insert(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int insertSelective(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    LogLogin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogLogin record);
}