package com.blog.dao.mapper.music;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.music.TMusic;

public interface TMusicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int insert(TMusic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int insertSelective(TMusic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    TMusic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMusic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TMusic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMusic record);

	int getCount(@Param("name")String name,@Param("startDate") Date start,@Param("endDate") Date end);

	List<TMusic> getDateByPage(@Param("name")String name,@Param("begin") int pageStartNumber,@Param("end") int pageEndNumber,
			@Param("startDate") Date start,@Param("endDate") Date end);
	
}