package com.blog.dao.mapper.music;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.music.TMusic;
import com.blog.dao.bean.music.TMusicType;

public interface TMusicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    int insert(TMusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    int insertSelective(TMusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    TMusicType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TMusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_music_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TMusicType record);

	int getCount(@Param("name")String name,@Param("startDate") Date start,@Param("endDate") Date end);

	List<TMusicType> getDateByPage(@Param("name")String name,@Param("begin") int pageStartNumber,@Param("end") int pageEndNumber,
			@Param("startDate") Date start,@Param("endDate") Date end);
}