package com.blog.dao.mapper.sys;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.sys.SysRuleUserrole;

public interface SysRuleUserroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int insert(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    SysRuleUserrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleUserrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_userrole
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleUserrole record);
    
    //获取该用户所有角色
	List<SysRuleUserrole> getAllByUserID(@Param("id") Long id);
	//删除该用户所有角色
	Integer deleteByUserId(@Param("id") Long id);
}