package com.blog.dao.mapper.sys;

import com.blog.dao.bean.sys.SysRulePrivilege;

public interface SysRulePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int insert(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int insertSelective(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    SysRulePrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRulePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRulePrivilege record);
}