package com.blog.dao.mapper.sys;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.sys.SysRuleRole;

public interface SysRuleRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    int insert(SysRuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    int insertSelective(SysRuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    SysRuleRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_rule_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRuleRole record);

	int getCount(@Param("startDate") Date startDate,@Param("endDate") Date endDate,@Param("state") Integer state);
	List<SysRuleRole> getRoleByPage(@Param("star")int pageStartNumber,@Param("end") int pageEndNumber,@Param("startDate") Date startDate,@Param("endDate") Date endDate,@Param("state")  Integer state);

	//获取所有角色
	List<SysRuleRole> getAll();
	//根据ID查找角色
	SysRuleRole getRoleById(@Param("id") Long id);
}