package com.blog.dao.mapper.sys;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.blog.dao.bean.sys.SysUser;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUser record);
    
    SysUser findUser(@Param("account")String account,@Param("pwd") String pwd);
    
    //获取用户数量
	int getCount(@Param("isTrue")Integer isTrue,@Param("startDate") Date startDate,@Param("endDate") Date endDate);

	/**
	 * 分页获取后台用户列表
	 * @param limit 一页数量
	 * @param offset 当前页码
	 * @return
	 */
	List<SysUser> getUserByPage(@Param("star") int star,@Param("end") int end,@Param("isTrue")Integer isTrue,@Param("startDate") Date startDate,@Param("endDate") Date endDate);
	//账号名不允许重复
	SysUser findUserByAccount(@Param("account") String account);
}