package com.blog.dao.bean.log;

import java.util.Date;

public class LogAdminAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.oper_id
     *
     * @mbggenerated
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.class_path
     *
     * @mbggenerated
     */
    private String classPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.oper
     *
     * @mbggenerated
     */
    private Integer oper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_admin_action.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.id
     *
     * @return the value of log_admin_action.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.id
     *
     * @param id the value for log_admin_action.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.oper_id
     *
     * @return the value of log_admin_action.oper_id
     *
     * @mbggenerated
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.oper_id
     *
     * @param operId the value for log_admin_action.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.user_name
     *
     * @return the value of log_admin_action.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.user_name
     *
     * @param userName the value for log_admin_action.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.ip
     *
     * @return the value of log_admin_action.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.ip
     *
     * @param ip the value for log_admin_action.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.ip_address
     *
     * @return the value of log_admin_action.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.ip_address
     *
     * @param ipAddress the value for log_admin_action.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.type
     *
     * @return the value of log_admin_action.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.type
     *
     * @param type the value for log_admin_action.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.class_path
     *
     * @return the value of log_admin_action.class_path
     *
     * @mbggenerated
     */
    public String getClassPath() {
        return classPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.class_path
     *
     * @param classPath the value for log_admin_action.class_path
     *
     * @mbggenerated
     */
    public void setClassPath(String classPath) {
        this.classPath = classPath == null ? null : classPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.remarks
     *
     * @return the value of log_admin_action.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.remarks
     *
     * @param remarks the value for log_admin_action.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.oper
     *
     * @return the value of log_admin_action.oper
     *
     * @mbggenerated
     */
    public Integer getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.oper
     *
     * @param oper the value for log_admin_action.oper
     *
     * @mbggenerated
     */
    public void setOper(Integer oper) {
        this.oper = oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_admin_action.create_date
     *
     * @return the value of log_admin_action.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_admin_action.create_date
     *
     * @param createDate the value for log_admin_action.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}