package com.blog.dao.bean.log;

import java.util.Date;

public class LogLogin {
    
    private Long id;
    private String loginName;
    private String ip;
    private String ipAddress;
    private Integer result;
    private String resultContent;
    private Integer clientDevice;
    private Integer oper;
    private Date createTime;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.id
     *
     * @param id the value for log_login.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.login_name
     *
     * @return the value of log_login.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.login_name
     *
     * @param loginName the value for log_login.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.ip
     *
     * @return the value of log_login.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.ip
     *
     * @param ip the value for log_login.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.ip_address
     *
     * @return the value of log_login.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.ip_address
     *
     * @param ipAddress the value for log_login.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.result
     *
     * @return the value of log_login.result
     *
     * @mbggenerated
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.result
     *
     * @param result the value for log_login.result
     *
     * @mbggenerated
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.result_content
     *
     * @return the value of log_login.result_content
     *
     * @mbggenerated
     */
    public String getResultContent() {
        return resultContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.result_content
     *
     * @param resultContent the value for log_login.result_content
     *
     * @mbggenerated
     */
    public void setResultContent(String resultContent) {
        this.resultContent = resultContent == null ? null : resultContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.client_device
     *
     * @return the value of log_login.client_device
     *
     * @mbggenerated
     */
    public Integer getClientDevice() {
        return clientDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.client_device
     *
     * @param clientDevice the value for log_login.client_device
     *
     * @mbggenerated
     */
    public void setClientDevice(Integer clientDevice) {
        this.clientDevice = clientDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.oper
     *
     * @return the value of log_login.oper
     *
     * @mbggenerated
     */
    public Integer getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.oper
     *
     * @param oper the value for log_login.oper
     *
     * @mbggenerated
     */
    public void setOper(Integer oper) {
        this.oper = oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_login.create_time
     *
     * @return the value of log_login.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_login.create_time
     *
     * @param createTime the value for log_login.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}