package com.blog.dao.bean.log;

import java.util.Date;

public class LogResponse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.req_id
     *
     * @mbggenerated
     */
    private Long reqId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.sys_name
     *
     * @mbggenerated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.call_way
     *
     * @mbggenerated
     */
    private Integer callWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_response.response_msg
     *
     * @mbggenerated
     */
    private String responseMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.id
     *
     * @return the value of log_response.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.id
     *
     * @param id the value for log_response.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.create_time
     *
     * @return the value of log_response.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.create_time
     *
     * @param createTime the value for log_response.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.req_id
     *
     * @return the value of log_response.req_id
     *
     * @mbggenerated
     */
    public Long getReqId() {
        return reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.req_id
     *
     * @param reqId the value for log_response.req_id
     *
     * @mbggenerated
     */
    public void setReqId(Long reqId) {
        this.reqId = reqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.sys_name
     *
     * @return the value of log_response.sys_name
     *
     * @mbggenerated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.sys_name
     *
     * @param sysName the value for log_response.sys_name
     *
     * @mbggenerated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.api_name
     *
     * @return the value of log_response.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.api_name
     *
     * @param apiName the value for log_response.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.status
     *
     * @return the value of log_response.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.status
     *
     * @param status the value for log_response.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.call_way
     *
     * @return the value of log_response.call_way
     *
     * @mbggenerated
     */
    public Integer getCallWay() {
        return callWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.call_way
     *
     * @param callWay the value for log_response.call_way
     *
     * @mbggenerated
     */
    public void setCallWay(Integer callWay) {
        this.callWay = callWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_response.response_msg
     *
     * @return the value of log_response.response_msg
     *
     * @mbggenerated
     */
    public String getResponseMsg() {
        return responseMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_response.response_msg
     *
     * @param responseMsg the value for log_response.response_msg
     *
     * @mbggenerated
     */
    public void setResponseMsg(String responseMsg) {
        this.responseMsg = responseMsg == null ? null : responseMsg.trim();
    }
}