package com.blog.dao.bean.log;

public class LogRequestWithBLOBs extends LogRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.request_url
     *
     * @mbggenerated
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.params
     *
     * @mbggenerated
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.request_url
     *
     * @return the value of log_request.request_url
     *
     * @mbggenerated
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.request_url
     *
     * @param requestUrl the value for log_request.request_url
     *
     * @mbggenerated
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.params
     *
     * @return the value of log_request.params
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.params
     *
     * @param params the value for log_request.params
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}