package com.blog.dao.bean.log;

import java.util.Date;

public class LogRequest extends LogRequestKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.sys_name
     *
     * @mbggenerated
     */
    private String sysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.api_name
     *
     * @mbggenerated
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_request.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.sys_name
     *
     * @return the value of log_request.sys_name
     *
     * @mbggenerated
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.sys_name
     *
     * @param sysName the value for log_request.sys_name
     *
     * @mbggenerated
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.api_name
     *
     * @return the value of log_request.api_name
     *
     * @mbggenerated
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.api_name
     *
     * @param apiName the value for log_request.api_name
     *
     * @mbggenerated
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.ip_address
     *
     * @return the value of log_request.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.ip_address
     *
     * @param ipAddress the value for log_request.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_request.create_time
     *
     * @return the value of log_request.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_request.create_time
     *
     * @param createTime the value for log_request.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}