package com.blog.dao.bean.gather;

import java.util.Date;

public class GatherContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.is_top
     *
     * @mbggenerated
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.is_hot
     *
     * @mbggenerated
     */
    private Integer isHot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.onlinetime
     *
     * @mbggenerated
     */
    private Date onlinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.oper_id
     *
     * @mbggenerated
     */
    private Long operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.static_link
     *
     * @mbggenerated
     */
    private String staticLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.his_url
     *
     * @mbggenerated
     */
    private String hisUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.his_img
     *
     * @mbggenerated
     */
    private String hisImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gather_content.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.id
     *
     * @return the value of gather_content.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.id
     *
     * @param id the value for gather_content.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.is_top
     *
     * @return the value of gather_content.is_top
     *
     * @mbggenerated
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.is_top
     *
     * @param isTop the value for gather_content.is_top
     *
     * @mbggenerated
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.order_num
     *
     * @return the value of gather_content.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.order_num
     *
     * @param orderNum the value for gather_content.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.is_hot
     *
     * @return the value of gather_content.is_hot
     *
     * @mbggenerated
     */
    public Integer getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.is_hot
     *
     * @param isHot the value for gather_content.is_hot
     *
     * @mbggenerated
     */
    public void setIsHot(Integer isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.type
     *
     * @return the value of gather_content.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.type
     *
     * @param type the value for gather_content.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.title
     *
     * @return the value of gather_content.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.title
     *
     * @param title the value for gather_content.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.introduction
     *
     * @return the value of gather_content.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.introduction
     *
     * @param introduction the value for gather_content.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.pic
     *
     * @return the value of gather_content.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.pic
     *
     * @param pic the value for gather_content.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.onlinetime
     *
     * @return the value of gather_content.onlinetime
     *
     * @mbggenerated
     */
    public Date getOnlinetime() {
        return onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.onlinetime
     *
     * @param onlinetime the value for gather_content.onlinetime
     *
     * @mbggenerated
     */
    public void setOnlinetime(Date onlinetime) {
        this.onlinetime = onlinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.author
     *
     * @return the value of gather_content.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.author
     *
     * @param author the value for gather_content.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.status
     *
     * @return the value of gather_content.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.status
     *
     * @param status the value for gather_content.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.update_time
     *
     * @return the value of gather_content.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.update_time
     *
     * @param updateTime the value for gather_content.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.create_time
     *
     * @return the value of gather_content.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.create_time
     *
     * @param createTime the value for gather_content.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.oper_id
     *
     * @return the value of gather_content.oper_id
     *
     * @mbggenerated
     */
    public Long getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.oper_id
     *
     * @param operId the value for gather_content.oper_id
     *
     * @mbggenerated
     */
    public void setOperId(Long operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.static_link
     *
     * @return the value of gather_content.static_link
     *
     * @mbggenerated
     */
    public String getStaticLink() {
        return staticLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.static_link
     *
     * @param staticLink the value for gather_content.static_link
     *
     * @mbggenerated
     */
    public void setStaticLink(String staticLink) {
        this.staticLink = staticLink == null ? null : staticLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.version
     *
     * @return the value of gather_content.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.version
     *
     * @param version the value for gather_content.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.his_url
     *
     * @return the value of gather_content.his_url
     *
     * @mbggenerated
     */
    public String getHisUrl() {
        return hisUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.his_url
     *
     * @param hisUrl the value for gather_content.his_url
     *
     * @mbggenerated
     */
    public void setHisUrl(String hisUrl) {
        this.hisUrl = hisUrl == null ? null : hisUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.his_img
     *
     * @return the value of gather_content.his_img
     *
     * @mbggenerated
     */
    public String getHisImg() {
        return hisImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.his_img
     *
     * @param hisImg the value for gather_content.his_img
     *
     * @mbggenerated
     */
    public void setHisImg(String hisImg) {
        this.hisImg = hisImg == null ? null : hisImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gather_content.content
     *
     * @return the value of gather_content.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gather_content.content
     *
     * @param content the value for gather_content.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}