package com.blog.dao.bean.music;

import java.util.Date;

public class TMusic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_name
     *
     * @mbggenerated
     */
    private String musicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_auther
     *
     * @mbggenerated
     */
    private String musicAuther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_album
     *
     * @mbggenerated
     */
    private String musicAlbum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_img
     *
     * @mbggenerated
     */
    private String musicImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_type
     *
     * @mbggenerated
     */
    private Integer musicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_src
     *
     * @mbggenerated
     */
    private String musicSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.click_amount
     *
     * @mbggenerated
     */
    private Long clickAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music.music_lyric
     *
     * @mbggenerated
     */
    private String musicLyric;

    
    private Integer isState;//0:正常1未发布
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.id
     *
     * @return the value of t_music.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.id
     *
     * @param id the value for t_music.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_name
     *
     * @return the value of t_music.music_name
     *
     * @mbggenerated
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_name
     *
     * @param musicName the value for t_music.music_name
     *
     * @mbggenerated
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName == null ? null : musicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_auther
     *
     * @return the value of t_music.music_auther
     *
     * @mbggenerated
     */
    public String getMusicAuther() {
        return musicAuther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_auther
     *
     * @param musicAuther the value for t_music.music_auther
     *
     * @mbggenerated
     */
    public void setMusicAuther(String musicAuther) {
        this.musicAuther = musicAuther == null ? null : musicAuther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_album
     *
     * @return the value of t_music.music_album
     *
     * @mbggenerated
     */
    public String getMusicAlbum() {
        return musicAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_album
     *
     * @param musicAlbum the value for t_music.music_album
     *
     * @mbggenerated
     */
    public void setMusicAlbum(String musicAlbum) {
        this.musicAlbum = musicAlbum == null ? null : musicAlbum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_img
     *
     * @return the value of t_music.music_img
     *
     * @mbggenerated
     */
    public String getMusicImg() {
        return musicImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_img
     *
     * @param musicImg the value for t_music.music_img
     *
     * @mbggenerated
     */
    public void setMusicImg(String musicImg) {
        this.musicImg = musicImg == null ? null : musicImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_type
     *
     * @return the value of t_music.music_type
     *
     * @mbggenerated
     */
    public Integer getMusicType() {
        return musicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_type
     *
     * @param musicType the value for t_music.music_type
     *
     * @mbggenerated
     */
    public void setMusicType(Integer musicType) {
        this.musicType = musicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_src
     *
     * @return the value of t_music.music_src
     *
     * @mbggenerated
     */
    public String getMusicSrc() {
        return musicSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_src
     *
     * @param musicSrc the value for t_music.music_src
     *
     * @mbggenerated
     */
    public void setMusicSrc(String musicSrc) {
        this.musicSrc = musicSrc == null ? null : musicSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.create_time
     *
     * @return the value of t_music.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.create_time
     *
     * @param createTime the value for t_music.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.update_time
     *
     * @return the value of t_music.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.update_time
     *
     * @param updateTime the value for t_music.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.is_delete
     *
     * @return the value of t_music.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.is_delete
     *
     * @param isDelete the value for t_music.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.click_amount
     *
     * @return the value of t_music.click_amount
     *
     * @mbggenerated
     */
    public Long getClickAmount() {
        return clickAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.click_amount
     *
     * @param clickAmount the value for t_music.click_amount
     *
     * @mbggenerated
     */
    public void setClickAmount(Long clickAmount) {
        this.clickAmount = clickAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.type
     *
     * @return the value of t_music.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.type
     *
     * @param type the value for t_music.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music.music_lyric
     *
     * @return the value of t_music.music_lyric
     *
     * @mbggenerated
     */
    public String getMusicLyric() {
        return musicLyric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music.music_lyric
     *
     * @param musicLyric the value for t_music.music_lyric
     *
     * @mbggenerated
     */
    public void setMusicLyric(String musicLyric) {
        this.musicLyric = musicLyric == null ? null : musicLyric.trim();
    }

	public Integer getIsState() {
		return isState;
	}

	public void setIsState(Integer isState) {
		this.isState = isState;
	}
}