package com.blog.dao.bean.music;

import java.util.Date;

public class TMusicType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.type__img
     *
     * @mbggenerated
     */
    private String typeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.type_introduce
     *
     * @mbggenerated
     */
    private String typeIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.click_amount
     *
     * @mbggenerated
     */
    private Long clickAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_music_type.state
     *
     * @mbggenerated
     */
    private Integer state;

    private Integer isState;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.id
     *
     * @return the value of t_music_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.id
     *
     * @param id the value for t_music_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.type_name
     *
     * @return the value of t_music_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.type_name
     *
     * @param typeName the value for t_music_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.type__img
     *
     * @return the value of t_music_type.type__img
     *
     * @mbggenerated
     */
    public String getTypeImg() {
        return typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.type__img
     *
     * @param typeImg the value for t_music_type.type__img
     *
     * @mbggenerated
     */
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg == null ? null : typeImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.type_introduce
     *
     * @return the value of t_music_type.type_introduce
     *
     * @mbggenerated
     */
    public String getTypeIntroduce() {
        return typeIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.type_introduce
     *
     * @param typeIntroduce the value for t_music_type.type_introduce
     *
     * @mbggenerated
     */
    public void setTypeIntroduce(String typeIntroduce) {
        this.typeIntroduce = typeIntroduce == null ? null : typeIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.create_time
     *
     * @return the value of t_music_type.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.create_time
     *
     * @param createTime the value for t_music_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.update_time
     *
     * @return the value of t_music_type.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.update_time
     *
     * @param updateTime the value for t_music_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.is_delete
     *
     * @return the value of t_music_type.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.is_delete
     *
     * @param isDelete the value for t_music_type.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.click_amount
     *
     * @return the value of t_music_type.click_amount
     *
     * @mbggenerated
     */
    public Long getClickAmount() {
        return clickAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.click_amount
     *
     * @param clickAmount the value for t_music_type.click_amount
     *
     * @mbggenerated
     */
    public void setClickAmount(Long clickAmount) {
        this.clickAmount = clickAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_music_type.state
     *
     * @return the value of t_music_type.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_music_type.state
     *
     * @param state the value for t_music_type.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

	public Integer getIsState() {
		return isState;
	}

	public void setIsState(Integer isState) {
		this.isState = isState;
	}
}